# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- origin/master

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install SDK .Net Core 3.1.x'
  inputs:
    packageType: 'sdk'
    version: '3.1.x'  
      
- task: NuGetCommand@2
  displayName: 'Restore Nuget Packages'
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'

- task: MSBuild@1
  displayName: 'Build Solution as "$(BuildConfiguration)"'
  inputs:
    solution: '**/*.sln'

- task: VSTest@2
  displayName: 'Run Tests as "$(BuildConfiguration)"'
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      Project\Backend_.NetCore_3_1\StefaniniCore.MSTest.Tests\bin\$(BuildConfiguration)\netcoreapp3.1\StefaniniCore.MSTest.Tests.dll
      !Project\Backend_.NetCore_3_1\StefaniniCore.xUnit.Tests\bin\$(BuildConfiguration)\netcoreapp3.1\StefaniniCore.xUnit.Tests.dll
      !Project\Backend_.NetCore_3_1\StefaniniCore.Specflow.Tests\bin\$(BuildConfiguration)\netcoreapp3.1\StefaniniCore.Specflow.Tests.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    codeCoverageEnabled: true

- task: CopyFiles@2
  displayName: 'Copying Files'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    #Contents: '**\*.*'
    Contents: '**\Project\Backend_.NetCore_3_1\*.*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Generate Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'