# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- origin/master

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install SDK .Net Core 3.1.x'
  inputs:
    packageType: 'sdk'
    version: '3.1.x'  
      
- task: NuGetCommand@2
  displayName: 'Restore Nuget Packages'
  inputs:
    command: 'restore'
    restoreSolution: '$(Solution)'
    feedsToUse: 'select'

- task: MSBuild@1
  displayName: 'Build Solution as "$(BuildConfiguration)"'
  inputs:
    solution: '$(Solution)'

- task: VSTest@2
  displayName: 'Run Tests as "$(BuildConfiguration)"'
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\$(BuildConfiguration)\**\StefaniniCore.*.Tests.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    codeCoverageEnabled: true

- task: FileTransform@1
  displayName: Transform Configurations
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/**/*.zip'
    fileType: 'json'
    targetFiles: '-transform **\$(ProjectApiName)\appsettings.Production.json -json **\$(ProjectApiName)\appsettings.json'

- task: VSBuild@1
  displayName: 'MSBuild Publish API'
  inputs:
    solution: '$(ProjectApi)'
    msbuildArgs: '/t:Publish  /p:Configuration=Deploy /p:BuildingProject=true;OutDir=$(Build.ArtifactStagingDirectory)\ProjectAPI'
    configuration: '$(BuildConfiguration)'
    clean: true
    msbuildArchitecture: 'x64'

- task: VSBuild@1
  displayName: 'MSBuild Publish Web'
  inputs:
    solution: '$(ProjectWeb)'
    msbuildArgs: '/t:Publish /p:Configuration=Deploy /p:BuildingProject=true;OutDir=$(Build.ArtifactStagingDirectory)\ProjectWeb'
    configuration: '$(BuildConfiguration)'
    clean: true
    msbuildArchitecture: 'x64'

- task: PublishBuildArtifacts@1
  displayName: 'Generate Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'