# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- origin/master

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install SDK .Net Core 3.1.x'
  inputs:
    packageType: 'sdk'
    version: '3.1.x'  
      
- task: NuGetCommand@2
  displayName: 'Restore Nuget Packages'
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'

- task: MSBuild@1
  displayName: 'Build Solution'
  inputs:
    solution: '**/*.sln'

# DotNet Test
#- task: DotNetCoreCLI@2
#  inputs:
#    command: 'test'
#    projects: '**/*[Tt]est/*.csproj'
#    arguments: '--configuration $(BuildConfiguration)'

- task: VSTest@2
  displayName: 'Run Tests as "$(BuildConfiguration)"'
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*[Tt]est.dll
      !**\*[Tt]ests.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    codeCoverageEnabled: true

# Run Tests.
#- task: VSTest@2
#  inputs:
#   testSelector: 'testAssemblies'
#    testAssemblyVer2: |
#      $(Build.StagingDirectory)\*test*.dll
#      !**\obj\**
#    searchFolder: '$(Build.StagingDirectory)'

- task: CopyFiles@2
  displayName: 'Copying Files from "$(Build.SourcesDirectory)" to "$(Build.ArtifactStagingDirectory)"'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    #Contents: '**\*.*'
    Contents: 'Project\Backend_.NetCore_3_1\*.*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Generate Artifacts to "$(Build.ArtifactStagingDirectory)"'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'