# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- origin/master

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

steps:
# Install SDK .Net Core.
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.x'  
      
# Restore Nuget Packages.
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'

# Build Solution.
- task: MSBuild@1
  inputs:
    solution: '**/*.sln'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*test*.dll
      !**\*TestAdapter.dll
      !**\*xUnit*.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
  displayName: 'dotnet build $(buildConfiguration)'

# Run Tests.
#- task: VSTest@2
#  inputs:
#   testSelector: 'testAssemblies'
#    testAssemblyVer2: |
#      $(Build.StagingDirectory)\*test*.dll
#      !**\obj\**
#    searchFolder: '$(Build.StagingDirectory)'

# Copy Files.
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    #Contents: '**\*.*'
    Contents: 'Project\Backend_.NetCore_3_1\*.*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# Generate Artifacts.
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'