

CREATE DATABASE StefDb;

USE StefDb;

CREATE TABLE Task(
Id INT PRIMARY KEY IDENTITY(1,1),
Name VARCHAR(30) NOT NULL,
Description VARCHAR(150),
Is_Active BIT NOT NULL,
Date_Created DATETIME NOT NULL,
Date_Updated DATETIME NOT NULL
);

CREATE TABLE Profile_Type(
Id INT PRIMARY KEY IDENTITY(1,1),
Name VARCHAR (30) NOT NULL,
Is_Active BIT NOT NULL,
Date_Created DATETIME NOT NULL,
Date_Updated DATETIME NOT NULL
);

CREATE TABLE Profile_Type_Task(
Id INT PRIMARY KEY IDENTITY(1,1),
Task_Id INT NOT NULL,
Profile_Type_Id INT NOT NULL
);

ALTER TABLE Profile_Type_Task ADD CONSTRAINT Profile_Type_TaskFk FOREIGN KEY (Task_Id) REFERENCES Task(Id);
ALTER TABLE Profile_Type_Task ADD CONSTRAINT Profile_Type_Profile_TypeFk FOREIGN KEY (Profile_Type_Id) REFERENCES Profile_Type(Id);

CREATE TABLE User_System(
Id INT PRIMARY KEY IDENTITY(1,1),
User_Name VARCHAR(30) NOT NULL,
Password VARCHAR(30) NOT NULL,
Profile_Type_Id INT NOT NULL,
Is_Active BIT NOT NULL,
Date_Created DATETIME NOT NULL,
Date_Updated DATETIME NOT NULL
);

ALTER TABLE User_System ADD CONSTRAINT User_System_Profile_TypeFk FOREIGN KEY (Profile_Type_Id) REFERENCES Profile_Type(Id);



