CREATE DATABASE StefDb;
GO

USE StefDb;
GO

/* 
DROP TABLE UserSystem
GO

DROP TABLE ProfileTypeTask
GO

DROP TABLE Task
GO

DROP TABLE ProfileType
GO
*/

CREATE TABLE Task(
Id INT PRIMARY KEY IDENTITY(1,1),
Name VARCHAR(30) NOT NULL,
Description VARCHAR(150),
Is_Active BIT NOT NULL,
Date_Created DATETIME NOT NULL,
Date_Updated DATETIME NOT NULL
);
GO
CREATE TABLE ProfileType(
Id INT PRIMARY KEY IDENTITY(1,1),
Name VARCHAR (30) NOT NULL,
Is_Active BIT NOT NULL,
Date_Created DATETIME NOT NULL,
Date_Updated DATETIME NOT NULL
);
GO
CREATE TABLE ProfileTypeTask(
Id INT PRIMARY KEY IDENTITY(1,1),
Task_Id INT NOT NULL,
Profile_Type_Id INT NOT NULL
);
GO

ALTER TABLE ProfileTypeTask ADD CONSTRAINT ProfileTypeTaskFk FOREIGN KEY (Task_Id) REFERENCES Task(Id);
GO
ALTER TABLE ProfileTypeTask ADD CONSTRAINT ProfileTypeProfileTypeFk FOREIGN KEY (Profile_Type_Id) REFERENCES ProfileType(Id);
GO

CREATE TABLE UserSystem(
Id INT PRIMARY KEY IDENTITY(1,1),
User_Name VARCHAR(30) NOT NULL,
Password VARCHAR(30) NOT NULL,
Profile_Type_Id INT NOT NULL,
Is_Active BIT NOT NULL,
Date_Created DATETIME NOT NULL,
Date_Updated DATETIME NOT NULL
);
GO

ALTER TABLE UserSystem ADD CONSTRAINT UserSystemProfileTypeFk FOREIGN KEY (Profile_Type_Id) REFERENCES ProfileType(Id);
GO
